### ISSUE TITLE
contentBlockIds.flatMap is not a function

### ISSUE THREAD

**Issue by Jonovono** [NotionX/react-notion-x#23]
Hi, really excited about this project! However, when I run it I get the following error: Am I doing something wrong?

(node:37978) ExperimentalWarning: The dns.promises API is experimental
(node:37978) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
(node:37978) UnhandledPromiseRejectionWarning: TypeError: contentBlockIds.flatMap is not a function
    at NotionAPI.<anonymous> (/Users/jordan/Desktop/game-hub-web/node_modules/notion-client/build/cjs/notion-api.js:109:66)
    at step (/Users/jordan/Desktop/game-hub-web/node_modules/notion-client/build/cjs/notion-api.js:44:23)
    at Object.next (/Users/jordan/Desktop/game-hub-web/node_modules/notion-client/build/cjs/notion-api.js:25:53)
    at fulfilled (/Users/jordan/Desktop/game-hub-web/node_modules/notion-client/build/cjs/notion-api.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:37978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Using it like so:

```
  const recordMap = await notion.getPage("067dd719a912471ea9a3ac10710e7fdf", {
    fetchCollections: false,
  });

```

**Comment by transitive-bullshit** [comment]
Hey @Jonovono, what version of Node.js are you using?

We recommend at least Node 12 https://github.com/NotionX/react-notion-x/blob/master/package.json#L9

**Comment by Jonovono** [comment]
Ah, my bad, thanks @transitive-bullshit that seemed to work
