### ISSUE TITLE
Upgrading `notion-client` from 4.16.1 to 6.12.9 results in `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for .....test.ts`

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#314]
#### Description
I was trying to upgrade the notion client on the backend, but seems like it causes an error which does not let me run the tests anymore.
The previous version for `notion-client` that worked fine was `4.16.1`.
The current version that causes an error is `6.12.9`.
The error message tells the following:
```shell
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ...notion.test.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/...node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/...node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/...node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/...node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/...node_modules/mocha/lib/cli/run.js:374:5)
-
```

**Comment by 9oelM** [comment]
maybe because of esm. It's not cjs anymore. Are you using ts-node to `node --loader=ts-node/esm ./index.ts`? Also, in your tsconfig, you may need to have `"ts-node": { "esm": true }`.

**Comment by MartinXPN** [comment]
Thanks for your comment @9oelM I think that was it.
