### ISSUE TITLE
Code Block is not working

### ISSUE THREAD

**Issue by ChanghyeonYoon** [NotionX/react-notion-x#443]
#### Notion Test Page ID

I added to my page code block (https://changhyeon-yoon.notion.site/1fbc5dd82bb84340b1c23c5499de9271)
But by notion x, It is not appear with this error.
```
framework-d51ece3d757c7ed2.js:1 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (framework-d51ece3d757c7ed2.js:1:121813)
    at bs (framework-d51ece3d757c7ed2.js:1:109369)
    at gs (framework-d51ece3d757c7ed2.js:1:109297)
    at vs (framework-d51ece3d757c7ed2.js:1:109160)
    at as (framework-d51ece3d757c7ed2.js:1:105940)
    at ls (framework-d51ece3d757c7ed2.js:1:104491)
    at S (framework-d51ece3d757c7ed2.js:1:138451)
    at MessagePort.T (framework-d51ece3d757c7ed2.js:1:138985)
```
https://changhyeon.net/1fbc5dd82bb84340b1c23c5499de9271

**Comment by ChanghyeonYoon** [comment]
```
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
This error too

**Comment by coderlfm** [comment]
same error

**Comment by olivewind** [comment]
same error

**Comment by melalj** [comment]
Is this project no longer maintained?

**Comment by kaichii** [comment]
same error, but can't see it in development mode

**Comment by kaichii** [comment]
@ChanghyeonYoon I removed some unused prism components, then I don't see this error.
