### ISSUE TITLE
RequestError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by ademidun** [NotionX/react-notion-x#52]
This is the Notion page I am trying to access: https://www.notion.so/How-to-Start-a-Scholarship-on-Atila-e412e194b70b46698133927e760dd294

I am getting the following error:

```
RequestError: Cannot read property 'startsWith' of undefined
       at Request._makeRequest (~/project_root/node_modules/notion-client/node_modules/got/dist/source/core/index.js:1177:19)
       at Request (~/project_root/node_modules/notion-client/node_modules/got/dist/source/core/index.js:328:28)
       at urlToOptions (internal/url.js:1259:28)
       at Object.request (https.js:279:15)
       at ~/project_root/node_modules/agent-base/patch-core.js:23:20
       at Request._makeRequest (~/project_root/node_modules/notion-client/node_modules/got/dist/source/core/index.js:1124:43)
       at Request (~/project_root/node_modules/notion-client/node_modules/got/dist/source/core/index.js:328:28)
       at process._tickCallback (internal/process/next_tick.js:68:7) name: 'RequestError', code: undefined, timings: undefined }
```

If it helps,  I am using the [serverless framework](https://www.serverless.com/) and [serverless offline](https://www.serverless.com/plugins/serverless-offline) to run my node server in localhost.

Here is my code snippet:

```node
import { NotionAPI } from 'notion-client'
const api = new NotionAPI();
console.log("api", api);
let response;

try {
    // fetch a page's content, including all async blocks, collection queries, and signed urls
    response = await api.getPage("e412e194b70b46698133927e760dd294");
} catch (err) {
    console.log("getNotionPage", { err });
    response = {
        error: err.toString(),
    };
}
return response;
```

**Comment by ademidun** [comment]
This github issue seems to suggest it's caused by the version of Node I am running. I've upgraded from Node 8 to 10 to 12 and the issue is still occuring.

https://github.com/sindresorhus/got/issues/998

**Comment by transitive-bullshit** [comment]
Hey @ademidun, thanks for reaching out.

What version of Node.js are you running *exactly*?

**Comment by ademidun** [comment]
1. When I got `Cannot read property 'startsWith' of undefined`. I was running `node: v10.16.3 (npm v6.9.0)`
2. When I got `ECONNREFUSED 127.0.0.1:443`. I was running `v12.22.1` and `10.22.0` I tried both versions.

If it helps when I used `node v8.10.0 (npm v5.6.0)` I got a completely different error but I think that was due to `serverless-offilne` but perhaps it might help in debugging the source of the error.

```
'~/project_root/node_modules/notion-client/node_modules/got/dist/source/create.js:157',
  'const paginateEach = (async function* (url, options) {',
  '^',
  '',
'SyntaxError: Unexpected token *',
  'at createScript (vm.js:80:10)',
  'at Object.runInThisContext (vm.js:139:10)',
  'at Module._compile (module.js:616:28)',
  'at Object.Module._extensions..js (module.js:663:10)',
  'at Module.load (module.js:565:32)',
  'at tryModuleLoad (module.js:505:12)',
  'at Function.Module._load (module.js:497:3)',
  'at Module.require (module.js:596:17)',
  'at require (internal/module.js:11:18)',
  'at Object.<anonymous> ~/project_root/node_modules/notion-client/node_modules/got/dist/source/index.js:14:18)',
  'at Module._compile (module.js:652:30)',
  'at Object.Module._extensions..js (module.js:663:10)',
  'at Module.load (module.js:565:32)',
  'at tryModuleLoad (module.js:505:12)',
  'at Function.Module._load (module.js:497:3)',
  'at Module.require (module.js:596:17)',
  'at require (internal/module.js:11:18)',
  'at Object.<anonymous> ~/project_root/node_modules/notion-client/src/notion-api.ts:1:1)',
  'at Module._compile (module.js:652:30)',
  'at Object.Module._extensions..js (module.js:663:10)',
  'at Module.load (module.js:565:32)',
  'at tryModuleLoad (module.js:505:12)',
  'at Function.Module._load (module.js:497:3)',
  'at Module.require (module.js:596:17)',
  'at require (internal/module.js:11:18)',
  'at Object.<anonymous> ~/project_root/node_modules/notion-client/src/index.ts:1:1)',
  'at Module._compile (module.js:652:30)',
  'at Object.Module._extensions..js (module.js:663:10)',
  'at Module.load (module.js:565:32)',
  'at tryModuleLoad (module.js:505:12)',
  'at Function.Module._load (module.js:497:3)',
  'at Module.require (module.js:596:17)',
  'at require (internal/module.js:11:18)',
  'at Object.notion-client ~/project_root/.webpack/service/webpack:/external "notion-client":1:1)',
  'at __webpack_require__ ~/project_root/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object../notion/notionPages.js ~/project_root/.webpack/service/webpack:/notion/notionPages.js:1:1)',
  'at __webpack_require__ ~/project_root/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object../server.js ~/project_root/.webpack/service/webpack:/server.js:13:1)',
  'at __webpack_require__ ~/project_root/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at ./constants.js.Object.defineProperty.value ~/project_root/.webpack/service/webpack:/webpack/bootstrap:83:1)',
  'at Object.<anonymous> ~/project_root/.webpack/service/server.js:87:10)',
  'at Module._compile (module.js:652:30)',
  'at Object.Module._extensions..js (module.js:663:10)',
  'at Module.load (module.js:565:32)',
  'at tryModuleLoad (module.js:505:12)',
  'at Function.Module._load (module.js:497:3)',
  'at Module.require (module.js:596:17)',
  'at require (internal/module.js:11:18)',
  'at Object.createHandler ~/project_root/node_modules/serverless-offline/src/functionHelper.js:194:17)',
  'at handler ~/project_root/node_modules/serverless-offline/src/index.js:664:44)',
  'at module.exports.internals.Manager.execute ~/project_root/node_modules/@hapi/hapi/lib/toolkit.js:41:33)',
  'at Object.internals.handler ~/project_root/node_modules/@hapi/hapi/lib/handler.js:46:48)',
  'at exports.execute ~/project_root/node_modules/@hapi/hapi/lib/handler.js:31:36)',
  'at Request._lifecycle ~/project_root/node_modules/@hapi/hapi/lib/request.js:312:68)',
```

**Comment by transitive-bullshit** [comment]
We only officially support node >= 12. Note that node v8 is no longer supported by node.js.

The `startsWith` error with node v10 is expected since we don't support node v10.

The only error here we can really help with is the node v12 one.

`ECONNREFUSED 127.0.0.1:443` seems like an issue where your code is trying to access localhost; I would guess this has to do with the `serverless-offline`.

My advice would be to get your example with node >= 12 working *outside* of `serverless-offline` first by running node.js directly. Once that's working, then reintroduce serverless-offline and figure out what's going on there.

Best of luck.
